# Generated by Django 3.2 on 2026-02-24

from django.db import migrations, models


def dedupe_item_slugs(apps, schema_editor):
    Item = apps.get_model('core', 'Item')
    seen = set()

    for item in Item.objects.all().order_by('id'):
        base_slug = (item.slug or '').strip()
        if not base_slug:
            base_slug = f'item-{item.id}'

        candidate = base_slug
        counter = 2
        while candidate in seen:
            candidate = f'{base_slug}-{counter}'
            counter += 1

        if item.slug != candidate:
            item.slug = candidate
            item.save(update_fields=['slug'])

        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_category'),
    ]

    operations = [
        migrations.RunPython(dedupe_item_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
