from django.urls import path
from .views import (
    welcome_page,
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    OrderSuccessView,
    AccountView,
    AddressBookCreateView,
    AddressBookUpdateView,
    AddressBookDeleteView,
    AddressBookSetDefaultView,
    OrderHistoryView,
    OrderDetailView,
    CancelOrderView,
    WishlistView,
    add_to_wishlist,
    remove_from_wishlist,
    move_wishlist_to_cart,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    razorpay_callback
)

app_name = 'core'

urlpatterns = [
    path('', welcome_page, name='welcome'),
    path('home/', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('order-success/', OrderSuccessView.as_view(), name='order-success'),
    path('account/', AccountView.as_view(), name='account'),
    path('account/address/add/', AddressBookCreateView.as_view(), name='address-add'),
    path('account/address/<int:pk>/edit/', AddressBookUpdateView.as_view(), name='address-edit'),
    path('account/address/<int:pk>/delete/', AddressBookDeleteView.as_view(), name='address-delete'),
    path('account/address/<int:pk>/default/', AddressBookSetDefaultView.as_view(), name='address-default'),
    path('orders/', OrderHistoryView.as_view(), name='order-history'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/cancel/', CancelOrderView.as_view(), name='order-cancel'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('wishlist/add/<slug>/', add_to_wishlist, name='wishlist-add'),
    path('wishlist/remove/<slug>/', remove_from_wishlist, name='wishlist-remove'),
    path('wishlist/move-to-cart/<slug>/', move_wishlist_to_cart, name='wishlist-move-to-cart'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('payment/razorpay/callback/', razorpay_callback, name='razorpay-callback'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]
